name: DR2 Build Project
on:
  push:
    branches:
      - main

permissions: {}
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      next-version: ${{ steps.next-tag.outputs.next-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPGithubCodeDeploy
          aws-region: eu-west-2
          role-session-name: GitHubActionsRole
      - id: next-tag
        run: echo next-version=$(curl -s $GITHUB_API_URL/repos/nationalarchives/dr2-ingest/tags | jq -r '.[0].name' | awk -F. -v OFS=. '{ $3++; print }') >> "$GITHUB_OUTPUT"
      - run: |
          rm -rf target/outputs
          mkdir -p target/outputs
          sbt ingestLambdasRoot/assembly
          (cd ./python/lambdas/preingest-importer/ && bash deploy.sh)
          zip -jA preingest-importer python/lambdas/preingest-importer/lambda_function.py
          cp preingest-importer target/outputs/preingest-tdr-importer
          cp preingest-importer target/outputs/preingest-dri-importer
          cp preingest-importer target/outputs/preingest-adhoc-importer
          cp preingest-importer target/outputs/preingest-restore-importer
          zip -jA ingest-metric-collector python/lambdas/ingest-metric-collector/ingest_metric_collector.py
          zip -jA pause-ingest python/lambdas/pause-ingest/pause_ingest.py
          zip -jA pause-preservica-activity python/lambdas/pause-preservica-activity/pause_preservica_activity.py
          zip -jA postingest-state-change-queue-sender python/lambdas/postingest-state-change-queue-sender/state_change_queue_sender.py
          zip -jA ip-lock-checker python/lambdas/ip-lock-checker/ip_lock_checker.py
          cp ingest-metric-collector target/outputs
          cp pause-ingest target/outputs
          cp pause-preservica-activity target/outputs
          cp postingest-state-change-queue-sender target/outputs
          cp ip-lock-checker target/outputs
          python .github/scripts/upload_files.py target/outputs $NEXT_VERSION 
          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION
        env:
          NEXT_VERSION: ${{ steps.next-tag.outputs.next-version }}
          GH_TOKEN: ${{ github.token }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=$NEXT_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          NEXT_VERSION: ${{ needs.pre-deploy.outputs.next-version }}
